module.exports = {
    roles: ['employee', 'hr', 'manager', 'finance', 'director', 'admin'],
    leaveTypes: ['Annual', 'Sick', 'Maternity', 'Hajj', 'Unpaid'],
    approvalModules: ['leave', 'expense', 'advance', 'payroll', 'appraisal', 'onboarding', 'bank_update'],
    approvalStatuses: ['pending', 'approved', 'rejected'],
    payrollStatuses: ['draft', 'reviewed', 'approved', 'finalized'],
    attendanceStatuses: ['present', 'absent', 'late', 'halfday', 'holiday', 'weekend', 'leave'],
    advanceTypes: ['salary', 'travel', 'emergency'],
    expenseTypes: ['Airfare', 'Hotel', 'Local Travel', 'Meals', 'Visa', 'Miscellaneous'],
    appraisalTypes: ['annual', 'probation', 'project'],
    contractTypes: ['Limited', 'Unlimited'],
    visaTypes: ['Employment', 'Partner', 'Investor', 'Family'],
    uaePublicHolidays2026: [
        { name: 'New Year\'s Day', date: '2026-01-01' },
        { name: 'Eid Al Fitr', date: '2026-03-20' },
        { name: 'Eid Al Fitr', date: '2026-03-21' },
        { name: 'Eid Al Fitr', date: '2026-03-22' },
        { name: 'Arafat Day', date: '2026-05-27' },
        { name: 'Eid Al Adha', date: '2026-05-28' },
        { name: 'Eid Al Adha', date: '2026-05-29' },
        { name: 'Eid Al Adha', date: '2026-05-30' },
        { name: 'Islamic New Year', date: '2026-06-17' },
        { name: 'Prophet Muhammad Birthday', date: '2026-08-27' },
        { name: 'Commemoration Day', date: '2026-12-01' },
        { name: 'UAE National Day', date: '2026-12-02' },
        { name: 'UAE National Day', date: '2026-12-03' },
    ],
    gratuity: {
        daysPerYearUnder5: 21,
        daysPerYearOver5: 30,
        minServiceYears: 1,
    },
    leaveAccrual: {
        daysPerMonth: 2.5,
        annualEntitlement: 30,
    },
    sickLeaveRules: {
        fullPay: 15,
        halfPay: 30,
        unpaid: 45,
    },
};
